##問2
##EMPLOYEE_MSTテーブルをemMst、enEnrをEMPLOYEE_ENROLLMENT
SELECT emMst.EMPLOYEE_ID , emMst.EMPLOYEE_NM , emMst.SEX
	FROM EMPLOYEE_MST emMst,
		 EMPLOYEE_ENROLLMENT enEnr
		 #社員IDを両テーブルの社員ID
	WHERE emMst.EMPLOYEE_ID = enEnr.EMPLOYEE_ID
	AND emMst.SEX = 1
	AND enEnr.RETIRED_FLG = 0
ORDER BY emMst.EMPLOYEE_ID ;
		