##問1
##駆動テーブルをEMPLOYEE_MST　EMPLOYEE_MSTテーブルをemMst、enDateをEMPLOYEE_ENROLLMENT
SELECT emMst.EMPLOYEE_ID , emMst.EMPLOYEE_NM , enDate.ENTERING_DATE
	  FROM EMPLOYEE_MST emMst INNER JOIN EMPLOYEE_ENROLLMENT enDate
	  ON emMst.EMPLOYEE_ID = enDate.EMPLOYEE_ID
 ORDER BY emMst.EMPLOYEE_ID ;
 