##問1
##EMPLOYEE_MSTテーブルをemMst、enEnrをEMPLOYEE_ENROLLMENT
SELECT emMst.EMPLOYEE_ID , emMst.EMPLOYEE_NM , enEnr.ENTERING_DATE
	  FROM EMPLOYEE_MST emMst INNER JOIN EMPLOYEE_ENROLLMENT enEnr
	  ON emMst.EMPLOYEE_ID = enEnr.EMPLOYEE_ID
 ORDER BY emMst.EMPLOYEE_ID ;
 
