##問1
##EMPLOYEE_MSTテーブルをemMst、emEnrをEMPLOYEE_ENROLLMENT
SELECT emMst.EMPLOYEE_ID , emMst.EMPLOYEE_NM , emEnr.ENTERING_DATE
	  FROM EMPLOYEE_MST emMst INNER JOIN EMPLOYEE_ENROLLMENT emEnr
	  ON emMst.EMPLOYEE_ID = emEnr.EMPLOYEE_ID
 ORDER BY emMst.EMPLOYEE_ID ;




