##問11
##EMPLOYEE_MSTテーブルをemMst、EMPLOYEE_ENROLLMENTをemEnr、DIVISION_MSTをdivMst、EMPLOYEE_CAREER_HSTをemCar
##2017/04/01時点で所属している部署とその人数
SELECT  divMst.DIVISION_CD , 
		MAX(divMst.DIVISION_NM) AS DIVISION_NM , 
		COUNT(emEnr.EMPLOYEE_ID) AS COUNT_MEMBER
  FROM EMPLOYEE_ENROLLMENT emEnr INNER JOIN EMPLOYEE_CAREER_HST emCar
                    		     ON emEnr.EMPLOYEE_ID = emCar.EMPLOYEE_ID
                    		     INNER JOIN DIVISION_MST divMst
                    		     ON emCar.DIVISION_CD = divMst.DIVISION_CD
	WHERE emEnr.RETIRED_FLG = 0 
			 AND date('2017-04-01') BETWEEN emCar.START_DATE AND emCar.FINISH_DATE 
	GROUP BY DIVISION_CD
	ORDER BY divMst.DIVISION_CD ;
