
##問12
##EMPLOYEE_MSTテーブルをemMst、EMPLOYEE_ENROLLMENTをemEnr、DIVISION_MSTをdivMst、EMPLOYEE_CAREER_HSTをemCar
SELECT  divMst.DIVISION_CD, divMst.DIVISION_NM, 
		AVG(TIMESTAMPDIFF(YEAR,emMst.BIRTH_DATE,'2017-04-01')) AS AVERAGE_AGE
  FROM EMPLOYEE_MST emMst INNER JOIN EMPLOYEE_ENROLLMENT emEnr 
 								 ON  emMst.EMPLOYEE_ID = emEnr.EMPLOYEE_ID 
  								 INNER JOIN EMPLOYEE_CAREER_HST emCar
                        		 ON emEnr.EMPLOYEE_ID = emCar.EMPLOYEE_ID
                          	     INNER JOIN DIVISION_MST divMst 
                          	   	 ON emCar.DIVISION_CD = divMst.DIVISION_CD
WHERE emEnr.RETIRED_FLG = 0 
	AND DATE('2017-04-01') BETWEEN emCar.START_DATE AND emCar.FINISH_DATE
GROUP BY DIVISION_CD HAVING ROUND(AVG(TIMESTAMPDIFF(YEAR,emMst.BIRTH_DATE,'2017-04-01')),1 )< 37
ORDER BY divMst.DIVISION_CD ;
