##問13
##EMPLOYEE_MSTテーブルをemMst、EMPLOYEE_ENROLLMENTをemEnr、DIVISION_MSTをdivMst、EMPLOYEE_CAREER_HSTをemCar
##在籍期間
SELECT  emMst.EMPLOYEE_ID, emMst.EMPLOYEE_NM,emCar.DIVISION_CD, divMst.DIVISION_NM,
			##開始から終了まで2017-04-01時点での在籍期間。MAX(c.DIVISION_NM)  AS DIVISION_NM 
			SUM(CASE WHEN ('2017-04-01' BETWEEN emCar.START_DATE AND emCar.FINISH_DATE)
			##入社して2017-04-01時点までの在籍期間。
			THEN TIMESTAMPDIFF(MONTH, emCar.START_DATE ,'2017-04-01') 
			##入社してから退職までの期間
		 	ELSE TIMESTAMPDIFF(MONTH, emCar.START_DATE ,emCar.FINISH_DATE) END )AS EMPLOYEE_PERIOD_M

	FROM EMPLOYEE_MST emMst INNER JOIN EMPLOYEE_CAREER_HST emCar
							ON emMst.EMPLOYEE_ID = emCar.EMPLOYEE_ID 
							INNER JOIN DIVISION_MST divMst 
                            ON emCar.DIVISION_CD = divMst.DIVISION_CD
	
	GROUP BY DIVISION_CD,EMPLOYEE_ID
	ORDER BY emMst.EMPLOYEE_ID, divMst.DIVISION_CD  ;






