##問2
##EMPLOYEE_MSTテーブルをemMst、emEnrをEMPLOYEE_ENROLLMENT
SELECT emMst.EMPLOYEE_ID , emMst.EMPLOYEE_NM , emMst.SEX
	FROM EMPLOYEE_MST emMst,
		 EMPLOYEE_ENROLLMENT emEnr
		 #社員IDを両テーブルの社員ID
	WHERE emMst.EMPLOYEE_ID = emEnr.EMPLOYEE_ID
	AND emMst.SEX = 1
	AND emEnr.RETIRED_FLG = 0
ORDER BY emMst.EMPLOYEE_ID ;
