##問3
##在籍している社員のうち2017/4/1時点で年齢が40以下の社員を年齢が低い順に取得
##EMPLOYEE_MSTテーブルをemMst、enEnrをEMPLOYEE_ENROLLMENT
SELECT emMst.EMPLOYEE_ID , emMst.EMPLOYEE_NM , emMst.BIRTH_DATE
	FROM EMPLOYEE_MST emMst INNER JOIN EMPLOYEE_ENROLLMENT emEnr 
	ON emMst.EMPLOYEE_ID = emEnr.EMPLOYEE_ID
	WHERE emEnr.RETIRED_FLG = 0 
	AND TIMESTAMPDIFF(YEAR,BIRTH_DATE,'2017-04-01') <= 40 
ORDER BY emMst.BIRTH_DATE DESC , emMst.EMPLOYEE_ID ;