##問4
##20代または50代の社員で年齢が高い順・
##EMPLOYEE_MSTテーブルをemMst、emEnrをEMPLOYEE_ENROLLMENT
SELECT emMst.EMPLOYEE_ID , emMst.EMPLOYEE_NM , emMst.BIRTH_DATE 
	FROM EMPLOYEE_MST emMst,
		 EMPLOYEE_ENROLLMENT emEnr
	WHERE emMst.EMPLOYEE_ID = emEnr.EMPLOYEE_ID
	AND emEnr.RETIRED_FLG = 0	
	##50代(50<=59)または20代(20<=29)
	AND (TIMESTAMPDIFF(YEAR,BIRTH_DATE,'2017-04-01') BETWEEN 20 AND 29
	OR TIMESTAMPDIFF(YEAR,BIRTH_DATE,'2017-04-01')BETWEEN 50 AND 59)
ORDER BY emMst.BIRTH_DATE ASC, emMst.EMPLOYEE_ID ;

