##問7
##EMPLOYEE_MSTテーブルをemMst、EMPLOYEE_ENROLLMENTをemEnr、DIVISION_CDをdivMst、EMPLOYEE_CAREER_HSTをemCar
SELECT emMst.EMPLOYEE_ID, emMst.EMPLOYEE_NM, divMst.DIVISION_NM
	FROM EMPLOYEE_MST emMst INNER JOIN EMPLOYEE_ENROLLMENT emEnr 
		ON emMst.EMPLOYEE_ID = emEnr.EMPLOYEE_ID
		INNER JOIN EMPLOYEE_CAREER_HST emCar 
		ON emEnr.EMPLOYEE_ID = emCar.EMPLOYEE_ID
		INNER JOIN DIVISION_MST  divMst
		ON emCar.DIVISION_CD = divMst.DIVISION_CD
WHERE emEnr.RETIRED_FLG = 0 
	AND  '2017-04-01' BETWEEN emCar.START_DATE AND emCar.FINISH_DATE
ORDER BY emMst.EMPLOYEE_ID ;

