
##問9

##EMPLOYEE_MSTテーブルをemMst、EMPLOYEE_ENROLLMENTをemEnr、DIVISION_MSTをdivMst、EMPLOYEE_CAREER_HSTをemCar
SELECT  COUNT(*) AS COUNT_EMPLOYEE,
		MIN(emMst.BIRTH_DATE)AS BIRTH_DATE_OLDEST,
		MAX(emMst.BIRTH_DATE)AS BIRTH_DATE_YNGEST,
		ROUND(AVG(TIMESTAMPDIFF(YEAR,emMst.BIRTH_DATE,'2017-04-01')),1) AS AVERAGE_AGE 
  FROM EMPLOYEE_MST emMst INNER JOIN EMPLOYEE_ENROLLMENT emEnr
                          ON emMst.EMPLOYEE_ID = emEnr.EMPLOYEE_ID
WHERE emEnr.RETIRED_FLG = 0   ;



